### ISSUE TITLE
Sledgehammer vs web-sys (long term)

### ISSUE THREAD

**Issue by Zizico2** [Demonthos/sledgehammer#29]
Assuming best case scenario for `web-sys`, let's say, one day, WASM will have full access to all the Web APIs, in a first class manner, just like JS does. Would this crate still be relevant?
At first glance I would say no, but `sledgehammer` beats `Vanilla JS` in some of the benchmarks in the readme, which would suggest this would have a place, even then.

What are your thoughts on that?

**Comment by ealmloff** [comment]
Once interface types are added I will likely depreciate sledgehammer.

The only reason sledgehammer can be faster than Vanilla JS ([here](https://github.com/Demonthos/wasm_bindgen_sledgehammer)) is because WASM is faster than JS. The row operations changing the arrays that store the rows are faster in WASM. The raw DOM operations are still slightly slower in WASM than JS.

**Comment by Zizico2** [comment]
Thanks for the quick response!

The interface types proposal is dead in the water but I assume https://github.com/WebAssembly/component-model has the same performance characteristics.

(also I assume you meant deprecate, not depreciate)

Closing
